
(defun syllabic-numeral-sg (char$)
  "Its argument should be a one-character string containing a digit."
  (if (not (stringp char$))
    (message "Error: argument char$ should be a string.")
    (if (not (= 1 (length char$)))
      (message "Error: argument char$ should contain only one character.")
      (cond
        ((string= char$ "1") "a")
        ((string= char$ "2") "e")
        ((string= char$ "3") "i")
        ((string= char$ "4") "o")
        ((string= char$ "5") "u")
        ((string= char$ "6") "ar")
        ((string= char$ "7") "er")
        ((string= char$ "8") "ir")
        ((string= char$ "9") "or")
        ((string= char$ "0") "ur")
        )
      )
    )
  )
					; (describe-function 'syllabic-numeral-sg)

(defun syllabic-numeral-tens (char$)
  "Its argument should be a one-character string containing a digit. The digit should have been extracted from the tens place of some numeral."
  (if (not (stringp char$))
    (message "Error: argument char$ should be a string.")
    (if (not (= 1 (length char$)))
      (message "Error: argument char$ should contain only one character.")
      (cond
        ((string= char$ "1") "W")
        ((string= char$ "2") "T")
        ((string= char$ "3") "H")
        ((string= char$ "4") "F")
        ((string= char$ "5") "V")
        ((string= char$ "6") "X")
        ((string= char$ "7") "S")
        ((string= char$ "8") "G")
        ((string= char$ "9") "N")
        ((string= char$ "0") "Z")
        )
      )
    )
  )
					; (describe-function 'syllabic-numeral-tens)

(defun syllabic-numeral-pr (pair$)
  "Its argument should be a two-character string containing only digits."
  (if (not (stringp pair$))
    (message "Error: argument pair$ should be a string.")
    (if (not (= 2 (length pair$)))
      (message "Error: argument pair$ should contain two characters.")
      (let (first$ second$ retval$)
        (setq first$ (substring pair$ 0 1))
        (setq second$ (substring pair$ 1 2))
        (setq retval$ (syllabic-numeral-tens first$))
        (setq retval$ (concat retval$ (syllabic-numeral-sg second$)))
        retval$
        )
      )
    )
  )
					; (describe-function 'syllabic-numeral-pr)

(defun syllabic-numeral-even (number$)
  "Its argument should be a string of digits of even length."
  (if (not (stringp number$))
    (message "Error: argument number$ should be a string.")
    (if (not (= 0 (% (length number$) 2)))
      (message "Error: the length of argument number$ should be even.")
      (let (output$ pair$)
        (setq output$ "")
        (while (> (length number$) 0)
          (setq pair$ (substring number$ 0 2))
          (setq number$ (substring number$ 2))
          (setq output$ (concat output$ (syllabic-numeral-pr pair$)))
          )
          output$
        )
      )
    )
  )
					; (describe-function 'syllabic-numeral-even)

(defun syllabic-numeral-odd (number$)
  "Its argument should be a string of digits of odd length."
  (if (not (stringp number$))
    (message "Error: argument number$ should be a string.")
    (if (not (= 1 (% (length number$) 2)))
      (message "Error: the length of argument number$ should be odd.")
      (let (output$ tail$ head$)
        (setq head$ (substring number$ 0 1))
        (setq tail$ (substring number$ 1))
        (setq output$ (syllabic-numeral-sg head$))
        (setq output$ (concat output$ (syllabic-numeral-even tail$)))
        output$
        )
      )
    )
  )
; (describe-function 'syllabic-numeral-odd)

(defun syllabic-numeral-str (number$)
  "Its argument should be a string of digits."
  (if (not (stringp number$))
    (message "Error: argument number$ should be a string.")
    (let (parity)
      (setq parity (% (length number$) 2))
      (cond
        ((= parity 0) (syllabic-numeral-even number$))
        ((= parity 1) (syllabic-numeral-odd number$))
        )
      )
    )
  )
					; (describe-function 'syllabic-numeral-str)

(defun syllabic-numeral (num)
  "Its argument num should be a non-negative integer."
  (if (not (numberp num))
    (message "Error: argument num should be a number.")
    (if (not (>= num 0))
      (message "Error: argument num should be non-negative.")
      (if (not (= (numberp (floor num))))
        (message "Error: argument num should be a non-negative integer.")
        (syllabic-numeral-str (number-to-string num))
        )
      )
    )
  )
; (describe-function 'syllabic-numeral)
